# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-23 08:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0010_auto_20171112_2322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(max_length=10)),
                ('comment', models.CharField(max_length=200)),
                ('seller_rate', models.IntegerField(max_length=10)),
                ('seller_comment', models.CharField(max_length=200)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.SearchItem')),
            ],
        ),
    ]
