# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-23 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0012_auto_20171123_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchitem',
            name='item_id',
        ),
        migrations.AddField(
            model_name='searchitem',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
