# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-23 08:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0014_remove_feedback_item_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchitem',
            name='id',
        ),
        migrations.AddField(
            model_name='feedback',
            name='item_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='search.SearchItem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='searchitem',
            name='item_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
