# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-23 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0015_auto_20171123_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchitem',
            name='location',
        ),
        migrations.AlterField(
            model_name='searchitem',
            name='detail',
            field=models.CharField(max_length=1000),
        ),
    ]
