# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-26 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0016_auto_20171123_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchitem',
            name='URLstrip',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='seller_rate',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='searchitem',
            name='detail',
            field=models.CharField(max_length=2000),
        ),
    ]
