# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-27 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0017_auto_20171126_2358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='seller_comment',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='seller_rate',
        ),
        migrations.AddField(
            model_name='searchitem',
            name='seller_rate',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='searchitem',
            name='rating',
            field=models.CharField(max_length=10),
        ),
    ]
