# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-27 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0019_searchitem_shipping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchitem',
            name='detail',
            field=models.CharField(max_length=10000),
        ),
    ]
